var searchData=
[
  ['final_5fy',['final_y',['../classDmpBbo_1_1Trajectory.html#aeb94e68102be7c8e5885e7f1ccf487e2',1,'DmpBbo::Trajectory']]],
  ['firstdimslicinginit',['firstDimSlicingInit',['../classDmpBbo_1_1FunctionApproximatorGMR.html#ab99de8c0d7c1870958e63f1bfc198303',1,'DmpBbo::FunctionApproximatorGMR']]],
  ['function_5fapproximator',['function_approximator',['../classDmpBbo_1_1Dmp.html#ac428e2dd848c99ddaf517f2dbacdf3ad',1,'DmpBbo::Dmp']]],
  ['functionapproximator',['FunctionApproximator',['../classDmpBbo_1_1FunctionApproximator.html',1,'DmpBbo']]],
  ['functionapproximator',['FunctionApproximator',['../classDmpBbo_1_1FunctionApproximator.html#ac004d40032d032dd823d8b41a2b09e4f',1,'DmpBbo::FunctionApproximator::FunctionApproximator(const MetaParameters *const meta_parameters, const ModelParameters *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximator.html#a7c402c9ebf0e21c94686f516f29a3a94',1,'DmpBbo::FunctionApproximator::FunctionApproximator(const ModelParameters *const model_parameters)'],['../classDmpBbo_1_1FunctionApproximator.html#a1d3363a4408af30b1251cbf7b4588f87',1,'DmpBbo::FunctionApproximator::FunctionApproximator(void)']]],
  ['functionapproximator_2ecpp',['FunctionApproximator.cpp',['../FunctionApproximator_8cpp.html',1,'']]],
  ['functionapproximator_2ehpp',['FunctionApproximator.hpp',['../FunctionApproximator_8hpp.html',1,'']]],
  ['functionapproximatorgmr',['FunctionApproximatorGMR',['../classDmpBbo_1_1FunctionApproximatorGMR.html',1,'DmpBbo']]],
  ['functionapproximatorgmr',['FunctionApproximatorGMR',['../classDmpBbo_1_1FunctionApproximatorGMR.html#a9434853efd2326bd0cb7412c13fe55d3',1,'DmpBbo::FunctionApproximatorGMR::FunctionApproximatorGMR(const MetaParametersGMR *const meta_parameters, const ModelParametersGMR *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorGMR.html#a7f7f6196ae263db36362c5aa2a8c6069',1,'DmpBbo::FunctionApproximatorGMR::FunctionApproximatorGMR(const ModelParametersGMR *const model_parameters)']]],
  ['functionapproximatorgmr_2ecpp',['FunctionApproximatorGMR.cpp',['../FunctionApproximatorGMR_8cpp.html',1,'']]],
  ['functionapproximatorgmr_2ehpp',['FunctionApproximatorGMR.hpp',['../FunctionApproximatorGMR_8hpp.html',1,'']]],
  ['functionapproximatorgpr',['FunctionApproximatorGPR',['../classDmpBbo_1_1FunctionApproximatorGPR.html',1,'DmpBbo']]],
  ['functionapproximatorgpr',['FunctionApproximatorGPR',['../classDmpBbo_1_1FunctionApproximatorGPR.html#afdf0d2f8b1ddfa701e58f7476da24f65',1,'DmpBbo::FunctionApproximatorGPR::FunctionApproximatorGPR(const MetaParametersGPR *const meta_parameters, const ModelParametersGPR *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorGPR.html#a24f8841f307c66117f585f639b0a464e',1,'DmpBbo::FunctionApproximatorGPR::FunctionApproximatorGPR(const ModelParametersGPR *const model_parameters)']]],
  ['functionapproximatorgpr_2ecpp',['FunctionApproximatorGPR.cpp',['../FunctionApproximatorGPR_8cpp.html',1,'']]],
  ['functionapproximatorgpr_2ehpp',['FunctionApproximatorGPR.hpp',['../FunctionApproximatorGPR_8hpp.html',1,'']]],
  ['functionapproximatorirfrls',['FunctionApproximatorIRFRLS',['../classDmpBbo_1_1FunctionApproximatorIRFRLS.html',1,'DmpBbo']]],
  ['functionapproximatorirfrls',['FunctionApproximatorIRFRLS',['../classDmpBbo_1_1FunctionApproximatorIRFRLS.html#ac41e9652816c7a26cb5bd3591c87f027',1,'DmpBbo::FunctionApproximatorIRFRLS::FunctionApproximatorIRFRLS(const MetaParametersIRFRLS *const meta_parameters, const ModelParametersIRFRLS *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorIRFRLS.html#a73cc6ae1afcc97d85774b142ea0755a1',1,'DmpBbo::FunctionApproximatorIRFRLS::FunctionApproximatorIRFRLS(const ModelParametersIRFRLS *const model_parameters)']]],
  ['functionapproximatorirfrls_2ecpp',['FunctionApproximatorIRFRLS.cpp',['../FunctionApproximatorIRFRLS_8cpp.html',1,'']]],
  ['functionapproximatorirfrls_2ehpp',['FunctionApproximatorIRFRLS.hpp',['../FunctionApproximatorIRFRLS_8hpp.html',1,'']]],
  ['functionapproximatorlwpr',['FunctionApproximatorLWPR',['../classDmpBbo_1_1FunctionApproximatorLWPR.html#ae20c704e818a6af0beb9189a4c37927b',1,'DmpBbo::FunctionApproximatorLWPR::FunctionApproximatorLWPR(const MetaParametersLWPR *const meta_parameters, const ModelParametersLWPR *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorLWPR.html#a4886bc268182a27dd0bdc62e9022d700',1,'DmpBbo::FunctionApproximatorLWPR::FunctionApproximatorLWPR(const ModelParametersLWPR *const model_parameters)']]],
  ['functionapproximatorlwpr',['FunctionApproximatorLWPR',['../classDmpBbo_1_1FunctionApproximatorLWPR.html',1,'DmpBbo']]],
  ['functionapproximatorlwpr_2ecpp',['FunctionApproximatorLWPR.cpp',['../FunctionApproximatorLWPR_8cpp.html',1,'']]],
  ['functionapproximatorlwpr_2ehpp',['FunctionApproximatorLWPR.hpp',['../FunctionApproximatorLWPR_8hpp.html',1,'']]],
  ['functionapproximatorlwr',['FunctionApproximatorLWR',['../classDmpBbo_1_1FunctionApproximatorLWR.html',1,'DmpBbo']]],
  ['functionapproximatorlwr',['FunctionApproximatorLWR',['../classDmpBbo_1_1FunctionApproximatorLWR.html#a614a73ce1a2298ddd81fe529dfd6ed91',1,'DmpBbo::FunctionApproximatorLWR::FunctionApproximatorLWR(const MetaParametersLWR *const meta_parameters, const ModelParametersLWR *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorLWR.html#aa2906d5457be398fbd1392fb623c9f3c',1,'DmpBbo::FunctionApproximatorLWR::FunctionApproximatorLWR(const ModelParametersLWR *const model_parameters)']]],
  ['functionapproximatorlwr_2ecpp',['FunctionApproximatorLWR.cpp',['../FunctionApproximatorLWR_8cpp.html',1,'']]],
  ['functionapproximatorlwr_2ehpp',['FunctionApproximatorLWR.hpp',['../FunctionApproximatorLWR_8hpp.html',1,'']]],
  ['functionapproximatorrbfn',['FunctionApproximatorRBFN',['../classDmpBbo_1_1FunctionApproximatorRBFN.html',1,'DmpBbo']]],
  ['functionapproximatorrbfn',['FunctionApproximatorRBFN',['../classDmpBbo_1_1FunctionApproximatorRBFN.html#ade257a456c5cd62773d5b55b8ccd0090',1,'DmpBbo::FunctionApproximatorRBFN::FunctionApproximatorRBFN(const MetaParametersRBFN *const meta_parameters, const ModelParametersRBFN *const model_parameters=NULL)'],['../classDmpBbo_1_1FunctionApproximatorRBFN.html#ac42696d1fbc10f2008fca4075482d860',1,'DmpBbo::FunctionApproximatorRBFN::FunctionApproximatorRBFN(const ModelParametersRBFN *const model_parameters)']]],
  ['functionapproximatorrbfn_2ecpp',['FunctionApproximatorRBFN.cpp',['../FunctionApproximatorRBFN_8cpp.html',1,'']]],
  ['functionapproximatorrbfn_2ehpp',['FunctionApproximatorRBFN.hpp',['../FunctionApproximatorRBFN_8hpp.html',1,'']]],
  ['function_20approximators',['Function Approximators',['../group__FunctionApproximators.html',1,'']]],
  ['function_20approximation_20module',['Function Approximation Module',['../page_func_approx.html',1,'']]]
];
