var searchData=
[
  ['main',['main',['../demoEvolutionaryOptimization_8cpp.html#a4c740be97d066078bad8e3997193c673',1,'main(int n_args, char *args[]):&#160;demoEvolutionaryOptimization.cpp'],['../demoEvolutionaryOptimizationTask_8cpp.html#a4c740be97d066078bad8e3997193c673',1,'main(int n_args, char *args[]):&#160;demoEvolutionaryOptimizationTask.cpp'],['../demoDmp_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoDmp.cpp'],['../demoDmpContextual_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoDmpContextual.cpp'],['../demoDmpTrainFromTrajectoryFile_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoDmpTrainFromTrajectoryFile.cpp'],['../demoDmpBbo_8cpp.html#a4c740be97d066078bad8e3997193c673',1,'main(int n_args, char *args[]):&#160;demoDmpBbo.cpp'],['../demoDmpBboMultiDim_8cpp.html#a4c740be97d066078bad8e3997193c673',1,'main(int n_args, char *args[]):&#160;demoDmpBboMultiDim.cpp'],['../demoImitationAndOptimization_8cpp.html#a4c740be97d066078bad8e3997193c673',1,'main(int n_args, char *args[]):&#160;demoImitationAndOptimization.cpp'],['../demoDynamicalSystems_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoDynamicalSystems.cpp'],['../demoExponentialSystem_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoExponentialSystem.cpp'],['../demoTrainFunctionApproximators_8cpp.html#a22577c6525b3f2fefecc0c741ba46a9a',1,'main(int n_args, char **args):&#160;demoTrainFunctionApproximators.cpp']]],
  ['mainpage_2ehpp',['mainpage.hpp',['../mainpage_8hpp.html',1,'']]],
  ['mass',['mass',['../classDmpBbo_1_1SpringDamperSystem.html#a387fcfdb067c6de3be9bfd61b868b839',1,'DmpBbo::SpringDamperSystem']]],
  ['maximum_5fcovariance',['maximum_covariance',['../classDmpBbo_1_1MetaParametersGPR.html#ae6f4fc553e04b571bd7349314c4e7cc3',1,'DmpBbo::MetaParametersGPR::maximum_covariance()'],['../classDmpBbo_1_1ModelParametersGPR.html#a298a9f1cca5f13135bb2b4334a56c734',1,'DmpBbo::ModelParametersGPR::maximum_covariance()']]],
  ['mean',['mean',['../classDmpBbo_1_1DistributionGaussian.html#a612f996501aac7e31237a21b47d03d72',1,'DmpBbo::DistributionGaussian']]],
  ['meanabsoluteerrorperoutputdimension',['meanAbsoluteErrorPerOutputDimension',['../demoTrainFunctionApproximators_8cpp.html#a718388cd48f1ddd8003e3cb4815d8c16',1,'demoTrainFunctionApproximators.cpp']]],
  ['metaparameters',['MetaParameters',['../classDmpBbo_1_1MetaParameters.html#af32e475115f403f9e1f3198ae9f4157b',1,'DmpBbo::MetaParameters::MetaParameters(int expected_input_dim)'],['../classDmpBbo_1_1MetaParameters.html#ae73979b117d45e439547c42eb1b4fc7b',1,'DmpBbo::MetaParameters::MetaParameters(void)']]],
  ['metaparameters',['MetaParameters',['../classDmpBbo_1_1MetaParameters.html',1,'DmpBbo']]],
  ['metaparameters_2ecpp',['MetaParameters.cpp',['../MetaParameters_8cpp.html',1,'']]],
  ['metaparameters_2ehpp',['MetaParameters.hpp',['../MetaParameters_8hpp.html',1,'']]],
  ['metaparametersgmr',['MetaParametersGMR',['../classDmpBbo_1_1MetaParametersGMR.html',1,'DmpBbo']]],
  ['metaparametersgmr',['MetaParametersGMR',['../classDmpBbo_1_1MetaParametersGMR.html#a63110f4ac8f8e509e5af3ca0fb762793',1,'DmpBbo::MetaParametersGMR']]],
  ['metaparametersgmr_2ecpp',['MetaParametersGMR.cpp',['../MetaParametersGMR_8cpp.html',1,'']]],
  ['metaparametersgmr_2ehpp',['MetaParametersGMR.hpp',['../MetaParametersGMR_8hpp.html',1,'']]],
  ['metaparametersgpr',['MetaParametersGPR',['../classDmpBbo_1_1MetaParametersGPR.html#a5e775025d3edb500d40a7bd01364bdd3',1,'DmpBbo::MetaParametersGPR::MetaParametersGPR(int expected_input_dim, double maximum_covariance, double sigma)'],['../classDmpBbo_1_1MetaParametersGPR.html#a355434471211dc4704a1bd59d188d182',1,'DmpBbo::MetaParametersGPR::MetaParametersGPR(int expected_input_dim, double maximum_covariance, const Eigen::VectorXd &amp;sigmas)']]],
  ['metaparametersgpr',['MetaParametersGPR',['../classDmpBbo_1_1MetaParametersGPR.html',1,'DmpBbo']]],
  ['metaparametersgpr_2ecpp',['MetaParametersGPR.cpp',['../MetaParametersGPR_8cpp.html',1,'']]],
  ['metaparametersgpr_2ehpp',['MetaParametersGPR.hpp',['../MetaParametersGPR_8hpp.html',1,'']]],
  ['metaparametersirfrls',['MetaParametersIRFRLS',['../classDmpBbo_1_1MetaParametersIRFRLS.html',1,'DmpBbo']]],
  ['metaparametersirfrls',['MetaParametersIRFRLS',['../classDmpBbo_1_1MetaParametersIRFRLS.html#a3db8bbd2524b2f2dcf3bfe4cd176ca8b',1,'DmpBbo::MetaParametersIRFRLS']]],
  ['metaparametersirfrls_2ecpp',['MetaParametersIRFRLS.cpp',['../MetaParametersIRFRLS_8cpp.html',1,'']]],
  ['metaparametersirfrls_2ehpp',['MetaParametersIRFRLS.hpp',['../MetaParametersIRFRLS_8hpp.html',1,'']]],
  ['metaparameterslwpr',['MetaParametersLWPR',['../classDmpBbo_1_1MetaParametersLWPR.html',1,'DmpBbo']]],
  ['metaparameterslwpr',['MetaParametersLWPR',['../classDmpBbo_1_1MetaParametersLWPR.html#ab1b0e2e29f5b63194a8cde678b8cb398',1,'DmpBbo::MetaParametersLWPR']]],
  ['metaparameterslwpr_2ecpp',['MetaParametersLWPR.cpp',['../MetaParametersLWPR_8cpp.html',1,'']]],
  ['metaparameterslwpr_2ehpp',['MetaParametersLWPR.hpp',['../MetaParametersLWPR_8hpp.html',1,'']]],
  ['metaparameterslwr',['MetaParametersLWR',['../classDmpBbo_1_1MetaParametersLWR.html',1,'DmpBbo']]],
  ['metaparameterslwr',['MetaParametersLWR',['../classDmpBbo_1_1MetaParametersLWR.html#ab75a1ee01157d2cc69a2a2335e344a2e',1,'DmpBbo::MetaParametersLWR::MetaParametersLWR(int expected_input_dim, const std::vector&lt; Eigen::VectorXd &gt; &amp;centers_per_dim, double intersection_height=0.5, bool asymmetric_kernels=false)'],['../classDmpBbo_1_1MetaParametersLWR.html#ac7dc1faef2a1b02d28b1a89c4aa2f50a',1,'DmpBbo::MetaParametersLWR::MetaParametersLWR(int expected_input_dim, const Eigen::VectorXi &amp;n_basis_functions_per_dim, double intersection_height=0.5, bool asymmetric_kernels=false)'],['../classDmpBbo_1_1MetaParametersLWR.html#ae1c43c06d41d4d4633c3da9ed7b7895f',1,'DmpBbo::MetaParametersLWR::MetaParametersLWR(int expected_input_dim, int n_basis_functions=10, double intersection_height=0.5, bool asymmetric_kernels=false)']]],
  ['metaparameterslwr_2ecpp',['MetaParametersLWR.cpp',['../MetaParametersLWR_8cpp.html',1,'']]],
  ['metaparameterslwr_2ehpp',['MetaParametersLWR.hpp',['../MetaParametersLWR_8hpp.html',1,'']]],
  ['metaparametersrbfn',['MetaParametersRBFN',['../classDmpBbo_1_1MetaParametersRBFN.html#a9ce4826ac71675b2bebe3a9d7e095de8',1,'DmpBbo::MetaParametersRBFN::MetaParametersRBFN(int expected_input_dim, const std::vector&lt; Eigen::VectorXd &gt; &amp;centers_per_dim, double intersection_height=0.5)'],['../classDmpBbo_1_1MetaParametersRBFN.html#a829cd0a2a44051113372839e96891467',1,'DmpBbo::MetaParametersRBFN::MetaParametersRBFN(int expected_input_dim, const Eigen::VectorXi &amp;n_basis_functions_per_dim, double intersection_height=0.5)'],['../classDmpBbo_1_1MetaParametersRBFN.html#af6d4ec88a62293f6f6783ef8814c1739',1,'DmpBbo::MetaParametersRBFN::MetaParametersRBFN(int expected_input_dim, int n_basis_functions=10, double intersection_height=0.5)']]],
  ['metaparametersrbfn',['MetaParametersRBFN',['../classDmpBbo_1_1MetaParametersRBFN.html',1,'DmpBbo']]],
  ['metaparametersrbfn_2ecpp',['MetaParametersRBFN.cpp',['../MetaParametersRBFN_8cpp.html',1,'']]],
  ['metaparametersrbfn_2ehpp',['MetaParametersRBFN.hpp',['../MetaParametersRBFN_8hpp.html',1,'']]],
  ['misc',['misc',['../classDmpBbo_1_1Trajectory.html#a4bd0eca2780012731ff1b64341be1cbc',1,'DmpBbo::Trajectory']]],
  ['modelparameters',['ModelParameters',['../classDmpBbo_1_1ModelParameters.html',1,'DmpBbo']]],
  ['modelparameters_2ecpp',['ModelParameters.cpp',['../ModelParameters_8cpp.html',1,'']]],
  ['modelparameters_2ehpp',['ModelParameters.hpp',['../ModelParameters_8hpp.html',1,'']]],
  ['modelparametersgmr',['ModelParametersGMR',['../classDmpBbo_1_1ModelParametersGMR.html#a248fa3b5f6d86e9316129b73863e9278',1,'DmpBbo::ModelParametersGMR']]],
  ['modelparametersgmr',['ModelParametersGMR',['../classDmpBbo_1_1ModelParametersGMR.html',1,'DmpBbo']]],
  ['modelparametersgmr_2ecpp',['ModelParametersGMR.cpp',['../ModelParametersGMR_8cpp.html',1,'']]],
  ['modelparametersgmr_2ehpp',['ModelParametersGMR.hpp',['../ModelParametersGMR_8hpp.html',1,'']]],
  ['modelparametersgpr',['ModelParametersGPR',['../classDmpBbo_1_1ModelParametersGPR.html',1,'DmpBbo']]],
  ['modelparametersgpr',['ModelParametersGPR',['../classDmpBbo_1_1ModelParametersGPR.html#a86bc19c8639d6a338726668c9d833278',1,'DmpBbo::ModelParametersGPR::ModelParametersGPR(const Eigen::MatrixXd &amp;train_inputs, const Eigen::VectorXd &amp;train_targets, const Eigen::MatrixXd &amp;gram, double maximum_covariance, double length)'],['../classDmpBbo_1_1ModelParametersGPR.html#a4c282bb545b3d48bb4b9d095d627c7fc',1,'DmpBbo::ModelParametersGPR::ModelParametersGPR(const Eigen::MatrixXd &amp;train_inputs, const Eigen::VectorXd &amp;train_targets, const Eigen::MatrixXd &amp;gram, double maximum_covariance, const Eigen::VectorXd &amp;sigmas)']]],
  ['modelparametersgpr_2ecpp',['ModelParametersGPR.cpp',['../ModelParametersGPR_8cpp.html',1,'']]],
  ['modelparametersgpr_2ehpp',['ModelParametersGPR.hpp',['../ModelParametersGPR_8hpp.html',1,'']]],
  ['modelparametersirfrls',['ModelParametersIRFRLS',['../classDmpBbo_1_1ModelParametersIRFRLS.html#a4b946b595de98eabadc9404ed201741f',1,'DmpBbo::ModelParametersIRFRLS']]],
  ['modelparametersirfrls',['ModelParametersIRFRLS',['../classDmpBbo_1_1ModelParametersIRFRLS.html',1,'DmpBbo']]],
  ['modelparametersirfrls_2ecpp',['ModelParametersIRFRLS.cpp',['../ModelParametersIRFRLS_8cpp.html',1,'']]],
  ['modelparametersirfrls_2ehpp',['ModelParametersIRFRLS.hpp',['../ModelParametersIRFRLS_8hpp.html',1,'']]],
  ['modelparameterslwpr',['ModelParametersLWPR',['../classDmpBbo_1_1ModelParametersLWPR.html',1,'DmpBbo']]],
  ['modelparameterslwpr',['ModelParametersLWPR',['../classDmpBbo_1_1ModelParametersLWPR.html#ad165c0cc27bd223f57aba5d82fd8f0aa',1,'DmpBbo::ModelParametersLWPR']]],
  ['modelparameterslwpr_2ecpp',['ModelParametersLWPR.cpp',['../ModelParametersLWPR_8cpp.html',1,'']]],
  ['modelparameterslwpr_2ehpp',['ModelParametersLWPR.hpp',['../ModelParametersLWPR_8hpp.html',1,'']]],
  ['modelparameterslwr',['ModelParametersLWR',['../classDmpBbo_1_1ModelParametersLWR.html',1,'DmpBbo']]],
  ['modelparameterslwr',['ModelParametersLWR',['../classDmpBbo_1_1ModelParametersLWR.html#a59a8b6f6a51c64625dc901a5446a23a3',1,'DmpBbo::ModelParametersLWR']]],
  ['modelparameterslwr_2ecpp',['ModelParametersLWR.cpp',['../ModelParametersLWR_8cpp.html',1,'']]],
  ['modelparameterslwr_2ehpp',['ModelParametersLWR.hpp',['../ModelParametersLWR_8hpp.html',1,'']]],
  ['modelparametersrbfn',['ModelParametersRBFN',['../classDmpBbo_1_1ModelParametersRBFN.html',1,'DmpBbo']]],
  ['modelparametersrbfn',['ModelParametersRBFN',['../classDmpBbo_1_1ModelParametersRBFN.html#a42878dcce6da0b2f6d477fd0685b978b',1,'DmpBbo::ModelParametersRBFN']]],
  ['modelparametersrbfn_2ecpp',['ModelParametersRBFN.cpp',['../ModelParametersRBFN_8cpp.html',1,'']]],
  ['modelparametersrbfn_2ehpp',['ModelParametersRBFN.hpp',['../ModelParametersRBFN_8hpp.html',1,'']]]
];
