var searchData=
[
  ['damping_5fcoefficient',['damping_coefficient',['../classDmpBbo_1_1SpringDamperSystem.html#a1e0acb1d6298104e74f81f53768f5bf1',1,'DmpBbo::SpringDamperSystem']]],
  ['democostfunctiondistancetopoint',['DemoCostFunctionDistanceToPoint',['../classDmpBbo_1_1DemoCostFunctionDistanceToPoint.html',1,'DmpBbo']]],
  ['democostfunctiondistancetopoint',['DemoCostFunctionDistanceToPoint',['../classDmpBbo_1_1DemoCostFunctionDistanceToPoint.html#a6d89a9e9f151cbac696edf37087b9aa2',1,'DmpBbo::DemoCostFunctionDistanceToPoint']]],
  ['demodmp_2ecpp',['demoDmp.cpp',['../demoDmp_8cpp.html',1,'']]],
  ['demodmpbbo_2ecpp',['demoDmpBbo.cpp',['../demoDmpBbo_8cpp.html',1,'']]],
  ['demodmpbbomultidim_2ecpp',['demoDmpBboMultiDim.cpp',['../demoDmpBboMultiDim_8cpp.html',1,'']]],
  ['demodmpcontextual_2ecpp',['demoDmpContextual.cpp',['../demoDmpContextual_8cpp.html',1,'']]],
  ['demodmptrainfromtrajectoryfile_2ecpp',['demoDmpTrainFromTrajectoryFile.cpp',['../demoDmpTrainFromTrajectoryFile_8cpp.html',1,'']]],
  ['demodynamicalsystems_2ecpp',['demoDynamicalSystems.cpp',['../demoDynamicalSystems_8cpp.html',1,'']]],
  ['demoevolutionaryoptimization_2ecpp',['demoEvolutionaryOptimization.cpp',['../demoEvolutionaryOptimization_8cpp.html',1,'']]],
  ['demoevolutionaryoptimizationtask_2ecpp',['demoEvolutionaryOptimizationTask.cpp',['../demoEvolutionaryOptimizationTask_8cpp.html',1,'']]],
  ['demoexponentialsystem_2ecpp',['demoExponentialSystem.cpp',['../demoExponentialSystem_8cpp.html',1,'']]],
  ['demoimitationandoptimization_2ecpp',['demoImitationAndOptimization.cpp',['../demoImitationAndOptimization_8cpp.html',1,'']]],
  ['demos',['Demos',['../group__Demos.html',1,'']]],
  ['demotaskapproximatequadraticfunction',['DemoTaskApproximateQuadraticFunction',['../classDemoTaskApproximateQuadraticFunction.html',1,'DemoTaskApproximateQuadraticFunction'],['../classDemoTaskApproximateQuadraticFunction.html#ac81f6a65537026fd59d52478253e1661',1,'DemoTaskApproximateQuadraticFunction::DemoTaskApproximateQuadraticFunction()']]],
  ['demotasksolverapproximatequadraticfunction',['DemoTaskSolverApproximateQuadraticFunction',['../classDemoTaskSolverApproximateQuadraticFunction.html',1,'DemoTaskSolverApproximateQuadraticFunction'],['../classDemoTaskSolverApproximateQuadraticFunction.html#ae4813da940a633221713aba3a12615c3',1,'DemoTaskSolverApproximateQuadraticFunction::DemoTaskSolverApproximateQuadraticFunction()']]],
  ['demotrainfunctionapproximators_2ecpp',['demoTrainFunctionApproximators.cpp',['../demoTrainFunctionApproximators_8cpp.html',1,'']]],
  ['differentialequation',['differentialEquation',['../classDmpBbo_1_1Dmp.html#ab564468764e7e4dc7c11e2a786e22c19',1,'DmpBbo::Dmp::differentialEquation()'],['../classDmpBbo_1_1DynamicalSystem.html#a70acc98a8e024f9b6e0e6de1b519e260',1,'DmpBbo::DynamicalSystem::differentialEquation()'],['../classDmpBbo_1_1ExponentialSystem.html#ab564468764e7e4dc7c11e2a786e22c19',1,'DmpBbo::ExponentialSystem::differentialEquation()'],['../classDmpBbo_1_1SigmoidSystem.html#ab564468764e7e4dc7c11e2a786e22c19',1,'DmpBbo::SigmoidSystem::differentialEquation()'],['../classDmpBbo_1_1SpringDamperSystem.html#ab564468764e7e4dc7c11e2a786e22c19',1,'DmpBbo::SpringDamperSystem::differentialEquation()'],['../classDmpBbo_1_1TimeSystem.html#ab564468764e7e4dc7c11e2a786e22c19',1,'DmpBbo::TimeSystem::differentialEquation()']]],
  ['dim',['dim',['../classDmpBbo_1_1Trajectory.html#a6f628f7f4ed9d77bf69f5b8560b98f18',1,'DmpBbo::Trajectory::dim()'],['../group__DynamicalSystems.html#ga6f628f7f4ed9d77bf69f5b8560b98f18',1,'DmpBbo::DynamicalSystem::dim()']]],
  ['dim_5fmisc',['dim_misc',['../classDmpBbo_1_1Trajectory.html#a54e86a99496037df2355a51d712f5d54',1,'DmpBbo::Trajectory']]],
  ['dim_5forig',['dim_orig',['../group__DynamicalSystems.html#ga93d7cbbf2e471b00f124e41706405a05',1,'DmpBbo::DynamicalSystem']]],
  ['distribution',['distribution',['../classDmpBbo_1_1UpdateSummary.html#a54b1ed1562d24d76c441110de5a0183f',1,'DmpBbo::UpdateSummary']]],
  ['distribution_5fnew',['distribution_new',['../classDmpBbo_1_1UpdateSummary.html#a85f1c35f510f89864f15029ea16e168c',1,'DmpBbo::UpdateSummary']]],
  ['distributiongaussian',['DistributionGaussian',['../classDmpBbo_1_1DistributionGaussian.html',1,'DmpBbo']]],
  ['distributiongaussian',['DistributionGaussian',['../classDmpBbo_1_1DistributionGaussian.html#a429296bb71ed97282ef49232431b7b51',1,'DmpBbo::DistributionGaussian']]],
  ['distributiongaussian_2ecpp',['DistributionGaussian.cpp',['../DistributionGaussian_8cpp.html',1,'']]],
  ['distributiongaussian_2ehpp',['DistributionGaussian.hpp',['../DistributionGaussian_8hpp.html',1,'']]],
  ['distributions',['distributions',['../classDmpBbo_1_1UpdateSummaryParallel.html#a8a18736c693cebddd78ee177f1b98072',1,'DmpBbo::UpdateSummaryParallel']]],
  ['distributions_5fnew',['distributions_new',['../classDmpBbo_1_1UpdateSummaryParallel.html#a4c6413f2fad88cc0c4addb3f2a2ef298',1,'DmpBbo::UpdateSummaryParallel']]],
  ['dmp',['Dmp',['../classDmpBbo_1_1Dmp.html',1,'DmpBbo']]],
  ['dmp',['Dmp',['../classDmpBbo_1_1Dmp.html#a4d4f5e7b4c2d8085355c228e2f8a9763',1,'DmpBbo::Dmp::Dmp(double tau, Eigen::VectorXd y_init, Eigen::VectorXd y_attr, std::vector&lt; FunctionApproximator * &gt; function_approximators, double alpha_spring_damper, DynamicalSystem *goal_system, DynamicalSystem *phase_system, DynamicalSystem *gating_system)'],['../classDmpBbo_1_1Dmp.html#a5861ed5fdc3e3472944c592414b4e8cb',1,'DmpBbo::Dmp::Dmp(int n_dims_dmp, std::vector&lt; FunctionApproximator * &gt; function_approximators, double alpha_spring_damper, DynamicalSystem *goal_system, DynamicalSystem *phase_system, DynamicalSystem *gating_system)'],['../classDmpBbo_1_1Dmp.html#a0a26f231a585e9f7f7f2d2dd571515b7',1,'DmpBbo::Dmp::Dmp(double tau, Eigen::VectorXd y_init, Eigen::VectorXd y_attr, std::vector&lt; FunctionApproximator * &gt; function_approximators, DmpType dmp_type=KULVICIUS_2012_JOINING)'],['../classDmpBbo_1_1Dmp.html#a30a4c3b7f5568b4d3f57e837241c4774',1,'DmpBbo::Dmp::Dmp(int n_dims_dmp, std::vector&lt; FunctionApproximator * &gt; function_approximators, DmpType dmp_type=KULVICIUS_2012_JOINING)'],['../classDmpBbo_1_1Dmp.html#a9e16b1345896b7f9cdf1158bb3708545',1,'DmpBbo::Dmp::Dmp(double tau, Eigen::VectorXd y_init, Eigen::VectorXd y_attr, double alpha_spring_damper, DynamicalSystem *goal_system)']]],
  ['dmp_2ecpp',['Dmp.cpp',['../Dmp_8cpp.html',1,'']]],
  ['dmp_2ehpp',['Dmp.hpp',['../Dmp_8hpp.html',1,'']]],
  ['dmpbbo',['DmpBBO',['../namespaceDmpBBO.html',1,'']]],
  ['dmpcontextual',['DmpContextual',['../classDmpBbo_1_1DmpContextual.html#a7ee70d54aba859cad05e07f0d2b1af88',1,'DmpBbo::DmpContextual']]],
  ['dmpcontextual',['DmpContextual',['../classDmpBbo_1_1DmpContextual.html',1,'DmpBbo']]],
  ['dmpcontextual_2ecpp',['DmpContextual.cpp',['../DmpContextual_8cpp.html',1,'']]],
  ['dmpcontextual_2ehpp',['DmpContextual.hpp',['../DmpContextual_8hpp.html',1,'']]],
  ['dmpcontextualonestep',['DmpContextualOneStep',['../classDmpBbo_1_1DmpContextualOneStep.html#a44bfebbc35616aefc17e43d4319e027e',1,'DmpBbo::DmpContextualOneStep::DmpContextualOneStep(int n_dims_dmp, std::vector&lt; FunctionApproximator * &gt; function_approximators, DmpType dmp_type=KULVICIUS_2012_JOINING)'],['../classDmpBbo_1_1DmpContextualOneStep.html#a8656352673dd315b46ef41b269c4051d',1,'DmpBbo::DmpContextualOneStep::DmpContextualOneStep(void)']]],
  ['dmpcontextualonestep',['DmpContextualOneStep',['../classDmpBbo_1_1DmpContextualOneStep.html',1,'DmpBbo']]],
  ['dmpcontextualonestep_2ecpp',['DmpContextualOneStep.cpp',['../DmpContextualOneStep_8cpp.html',1,'']]],
  ['dmpcontextualonestep_2ehpp',['DmpContextualOneStep.hpp',['../DmpContextualOneStep_8hpp.html',1,'']]],
  ['dmpcontextualtwostep',['DmpContextualTwoStep',['../classDmpBbo_1_1DmpContextualTwoStep.html',1,'DmpBbo']]],
  ['dmpcontextualtwostep',['DmpContextualTwoStep',['../classDmpBbo_1_1DmpContextualTwoStep.html#ae88d955cf82c0648ee8d304ab227be44',1,'DmpBbo::DmpContextualTwoStep::DmpContextualTwoStep(int n_dims_dmp, std::vector&lt; FunctionApproximator * &gt; function_approximators, FunctionApproximator *policy_parameter_function, DmpType dmp_type=KULVICIUS_2012_JOINING)'],['../classDmpBbo_1_1DmpContextualTwoStep.html#afd51892890cb0f9c67f020e736b6b1e3',1,'DmpBbo::DmpContextualTwoStep::DmpContextualTwoStep(void)']]],
  ['dmpcontextualtwostep_2ecpp',['DmpContextualTwoStep.cpp',['../DmpContextualTwoStep_8cpp.html',1,'']]],
  ['dmpcontextualtwostep_2ehpp',['DmpContextualTwoStep.hpp',['../DmpContextualTwoStep_8hpp.html',1,'']]],
  ['dynamic_20movement_20primitives',['Dynamic Movement Primitives',['../group__Dmps.html',1,'']]],
  ['dmptype',['DmpType',['../group__Dmps.html#gaccba8d09ec99ae66e469b3511bb232a4',1,'DmpBbo::Dmp']]],
  ['duration',['duration',['../classDmpBbo_1_1Trajectory.html#aa522350717a41ed129d693f0337b6247',1,'DmpBbo::Trajectory']]],
  ['dynamicalsystem',['DynamicalSystem',['../classDmpBbo_1_1DynamicalSystem.html',1,'DmpBbo']]],
  ['dynamicalsystem',['DynamicalSystem',['../classDmpBbo_1_1DynamicalSystem.html#a462231c16d651ba070ec880d1f2fd0b1',1,'DmpBbo::DynamicalSystem::DynamicalSystem(int order, double tau, Eigen::VectorXd initial_state, Eigen::VectorXd attractor_state, std::string name)'],['../classDmpBbo_1_1DynamicalSystem.html#a2619319384507480c48e61850037a461',1,'DmpBbo::DynamicalSystem::DynamicalSystem(void)']]],
  ['dynamicalsystem_2ecpp',['DynamicalSystem.cpp',['../DynamicalSystem_8cpp.html',1,'']]],
  ['dynamicalsystem_2ehpp',['DynamicalSystem.hpp',['../DynamicalSystem_8hpp.html',1,'']]],
  ['dynamical_20systems',['Dynamical Systems',['../group__DynamicalSystems.html',1,'']]],
  ['design_20rationale',['Design Rationale',['../page_design.html',1,'']]],
  ['dynamical_20movement_20primitives_20module',['Dynamical Movement Primitives Module',['../page_dmp.html',1,'']]],
  ['dynamical_20systems_20module',['Dynamical Systems Module',['../page_dyn_sys.html',1,'']]]
];
