var searchData=
[
  ['unifiedmodel',['UnifiedModel',['../classDmpBbo_1_1UnifiedModel.html#a597f14110f208256ba9124d9c839d520',1,'DmpBbo::UnifiedModel::UnifiedModel(const Eigen::MatrixXd &amp;centers, const Eigen::MatrixXd &amp;widths, const Eigen::VectorXd &amp;weights, bool normalized_basis_functions, bool lines_pivot_at_max_activation=false)'],['../classDmpBbo_1_1UnifiedModel.html#ab217b9dbb87440828bd80f294621f6ea',1,'DmpBbo::UnifiedModel::UnifiedModel(const Eigen::MatrixXd &amp;centers, const Eigen::MatrixXd &amp;widths, const Eigen::MatrixXd &amp;slopes, const Eigen::VectorXd &amp;offsets, bool normalized_basis_functions, bool lines_pivot_at_max_activation=false)'],['../classDmpBbo_1_1UnifiedModel.html#a805750e8fa38cebe8dd37ce1d161ef04',1,'DmpBbo::UnifiedModel::UnifiedModel(const Eigen::MatrixXd &amp;angular_frequencies, const Eigen::VectorXd &amp;phases, const Eigen::VectorXd &amp;weights)'],['../classDmpBbo_1_1UnifiedModel.html#afa95162d1e912a9d254a0e253fd5f87a',1,'DmpBbo::UnifiedModel::UnifiedModel(const std::vector&lt; Eigen::VectorXd &gt; &amp;centers, const std::vector&lt; Eigen::MatrixXd &gt; &amp;widths, const std::vector&lt; Eigen::VectorXd &gt; &amp;slopes, const std::vector&lt; double &gt; &amp;offsets, const std::vector&lt; double &gt; &amp;priors, bool normalized_basis_functions=false, bool lines_pivot_at_max_activation=false)']]],
  ['unnormalizedkernelactivations',['unnormalizedKernelActivations',['../classDmpBbo_1_1ModelParametersLWR.html#ad061d436c92cce36d0ed724774790a43',1,'DmpBbo::ModelParametersLWR']]],
  ['updatedistribution',['updateDistribution',['../classDmpBbo_1_1Updater.html#ae57a9f8264e9a9689fd21ef99c623227',1,'DmpBbo::Updater::updateDistribution(const DistributionGaussian &amp;distribution, const Eigen::MatrixXd &amp;samples, const Eigen::VectorXd &amp;costs, Eigen::VectorXd &amp;weights, DistributionGaussian &amp;distribution_new, UpdateSummary &amp;summary) const '],['../classDmpBbo_1_1Updater.html#a9f3c0a24eb032b84b724a19deb77efd8',1,'DmpBbo::Updater::updateDistribution(const DistributionGaussian &amp;distribution, const Eigen::MatrixXd &amp;samples, const Eigen::VectorXd &amp;costs, DistributionGaussian &amp;distribution_new) const '],['../classDmpBbo_1_1Updater.html#a4b660190fb18615402cbff5ececf9c2b',1,'DmpBbo::Updater::updateDistribution(const DistributionGaussian &amp;distribution, const Eigen::MatrixXd &amp;samples, const Eigen::VectorXd &amp;costs, DistributionGaussian &amp;distribution_new, UpdateSummary &amp;summary) const '],['../classDmpBbo_1_1Updater.html#ac7a91b073fbe6e73a10c14fb73bd9689',1,'DmpBbo::Updater::updateDistribution(const DistributionGaussian &amp;distribution, const Eigen::MatrixXd &amp;samples, const Eigen::VectorXd &amp;costs, Eigen::VectorXd &amp;weights, DistributionGaussian &amp;distribution_new) const =0'],['../classDmpBbo_1_1UpdaterCovarAdaptation.html#aabb65aaf08049416ed18b294d5fca415',1,'DmpBbo::UpdaterCovarAdaptation::updateDistribution()'],['../classDmpBbo_1_1UpdaterCovarDecay.html#aabb65aaf08049416ed18b294d5fca415',1,'DmpBbo::UpdaterCovarDecay::updateDistribution()'],['../classDmpBbo_1_1UpdaterMean.html#aabb65aaf08049416ed18b294d5fca415',1,'DmpBbo::UpdaterMean::updateDistribution()']]],
  ['updatedistributionmean',['updateDistributionMean',['../classDmpBbo_1_1UpdaterMean.html#a97c2ddfabeee67dba0044f405f4ce8c0',1,'DmpBbo::UpdaterMean']]],
  ['updatercovaradaptation',['UpdaterCovarAdaptation',['../classDmpBbo_1_1UpdaterCovarAdaptation.html#a33570a5da7912bcc2709355a7fa5d2e6',1,'DmpBbo::UpdaterCovarAdaptation']]],
  ['updatercovardecay',['UpdaterCovarDecay',['../classDmpBbo_1_1UpdaterCovarDecay.html#a51e57f2c597f88e95f2e2159ff40dc00',1,'DmpBbo::UpdaterCovarDecay']]],
  ['updatermean',['UpdaterMean',['../classDmpBbo_1_1UpdaterMean.html#a8164afea816503cb4179eb65145947da',1,'DmpBbo::UpdaterMean::UpdaterMean(double eliteness, std::string weighting_method=&quot;PI-BB&quot;)'],['../classDmpBbo_1_1UpdaterMean.html#a005e77ab55b2412bb2172b52bf263570',1,'DmpBbo::UpdaterMean::UpdaterMean(void)']]]
];
